defmodule SymphonyElixir.Coordinator.Directive.ProposeGuidanceUpdate do
  @moduledoc """
  Directive to create a GitHub issue that proposes a guidance update.

  The issue is labeled "guidance-update" and contains:
  - The detected pattern and its frequency
  - Whether the rule is missing or unclear
  - The target file (CLAUDE.md, ai_docs/, deep-review)
  - The specific suggested change
  - PR references where the pattern was observed

  A coding agent picks up this issue and makes the actual file changes,
  creating a meta-PR that updates the project's guidance. A human reviews
  and merges the guidance PR, closing the learning loop.
  """

  @enforce_keys [:project_id, :gap]
  defstruct [:project_id, :gap]
end

defimpl Jido.AgentServer.DirectiveExec,
  for: SymphonyElixir.Coordinator.Directive.ProposeGuidanceUpdate do
  require Logger

  def exec(%{project_id: project_id, gap: gap}, _input_signal, state) do
    repo =
      SymphonyElixir.Config.github_repo(project_id) || System.get_env("GITHUB_REPO")

    Logger.info(
      "DirectiveExec: proposing guidance update for #{gap.theme} in #{gap.target_file}"
    )

    title = build_title(gap)
    body = build_body(gap)

    case run_gh([
           "issue", "create",
           "--title", title,
           "--body", body,
           "--label", "Todo,guidance-update",
           "--repo", repo
         ]) do
      {:ok, url} ->
        Logger.info("DirectiveExec: guidance update issue created: #{url}")

      {:error, reason} ->
        Logger.error("DirectiveExec: failed to create guidance issue: #{inspect(reason)}")
    end

    {:ok, state}
  end

  defp build_title(gap) do
    action =
      case gap.classification do
        :rule_missing -> "add"
        :rule_unclear -> "strengthen"
        _ -> "update"
      end

    theme = gap.theme |> to_string() |> String.replace("_", " ")
    "fix(guidance): #{action} #{theme} rule in #{gap.target_file}"
  end

  defp build_body(gap) do
    pr_refs =
      (gap.prs || [])
      |> Enum.map(fn n -> "##{n}" end)
      |> Enum.join(", ")

    classification_label =
      case gap.classification do
        :rule_missing -> "No rule exists for this pattern"
        :rule_unclear -> "Rule exists but is too vague — agents still violate it"
        _ -> "Unknown"
      end

    sections = [
      "## Guidance Update Request",
      "",
      "The FeedbackAgent detected a recurring review pattern that indicates",
      "a gap in the project's coding guidance.",
      "",
      "### Pattern",
      "",
      "- **Theme:** #{gap.theme}",
      "- **Classification:** #{classification_label}",
      "- **Frequency:** Seen in #{gap.frequency} PRs (#{pr_refs})",
      "- **Target file:** `#{gap.target_file}`",
      ""
    ]

    sections =
      if gap.current_rule do
        sections ++ ["### Current Rule", "", "> #{gap.current_rule}", ""]
      else
        sections ++ ["### Current Rule", "", "_No existing rule found._", ""]
      end

    sections =
      sections ++
        [
          "### Suggested Change",
          "",
          gap.suggestion || "Review and add appropriate guidance.",
          "",
          "## Instructions",
          "",
          "1. Read the current content of `#{gap.target_file}`.",
          "2. Apply the suggested change (add new rule or strengthen existing one).",
          "3. If updating CLAUDE.md, ensure the rule is in the 'Code Rules (MUST FOLLOW)' section.",
          "4. If updating deep-review, assign an appropriate rule number (R13+).",
          "5. Keep rules concise and specific — include concrete examples of what to avoid.",
          "6. Run `/deep-review` on your changes to verify consistency.",
          "",
          "---",
          "_Auto-generated by FeedbackAgent from review pattern analysis._"
        ]

    Enum.join(sections, "\n")
  end

  defp run_gh(args) do
    case System.find_executable("gh") do
      nil ->
        {:error, :gh_not_installed}

      gh_path ->
        case System.cmd(gh_path, args, stderr_to_stdout: true) do
          {output, 0} -> {:ok, String.trim(output)}
          {output, code} -> {:error, {:gh_exit, code, String.slice(output, 0, 500)}}
        end
    end
  end
end
